### ISSUE TITLE
ValueError: Expected x_min for bbox (-0.14078849999999998, 0.187646, 0.2437165, 0.621276, 'no') to be in the range [0.0, 1.0], got -0.1407884999999999

### ISSUE THREAD

**Issue by howard-liang-B** [muhammad-faizan-122/yolo-data-augmentation#3]
Traceback (most recent call last):
  File "d:\Python Project\yolo-data-augmentation\run.py", line 4, in <module>
    run_pipeline()
  File "d:\Python Project\yolo-data-augmentation\controller\workflow.py", line 20, in run_pipeline
    apply_aug(image, album_bboxes, CONSTANTS["out_lab_pth"],  CONSTANTS["out_img_pth"], aug_file_name, CONSTANTS['CLASSES'])
  File "d:\Python Project\yolo-data-augmentation\controller\apply_album_aug.py", line 17, in apply_aug
    transformed = transform(image=image, bboxes=bboxes)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\composition.py", line 207, in __call__
    p.preprocess(data)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\utils.py", line 83, in preprocess
    data[data_name] = self.check_and_convert(data[data_name], rows, cols, direction="to")
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\utils.py", line 91, in check_and_convert
    return self.convert_to_albumentations(data, rows, cols)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\bbox_utils.py", line 142, in convert_to_albumentations
    return convert_bboxes_to_albumentations(data, self.params.format, rows, cols, check_validity=True)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\bbox_utils.py", line 408, in convert_bboxes_to_albumentations
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\bbox_utils.py", line 408, in <listcomp>
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\bbox_utils.py", line 352, in convert_bbox_to_albumentations
    check_bbox(bbox)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\bbox_utils.py", line 435, in check_bbox
    raise ValueError(f"Expected {name} for bbox {bbox} to be in the range [0.0, 1.0], got {value}.")
ValueError: Expected x_min for bbox (-0.14078849999999998, 0.187646, 0.2437165, 0.621276, 'no') to be in the range [0.0, 1.0], got -0.1407884999999999

I want to use in yolov8
This is my error when I run run.py

This is my labels in inp-ds/images/1.png

0 0.051464 0.404461 0.384505 0.433630
0 0.839169 0.528721 0.265285 0.501118
2 0.447081 0.556209 0.490889 0.612746

**Comment by howard-liang-B** [comment]
the error always come from 
transformed = transform(image=image, bboxes=bboxes)

def apply_aug(image, bboxes, out_lab_pth, out_img_pth, transformed_file_name, classes):
        transform = A.Compose([
            A.RandomCrop(width=300, height=300),
            A.HorizontalFlip(p=0.5),
            A.RandomBrightnessContrast(p=-1),
            A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0),
            A.CLAHE(clip_limit=(0, 1), tile_grid_size=(8, 8), always_apply=True),        
            A.Resize(300, 300)
        ], bbox_params=A.BboxParams(format='yolo'))
        transformed = transform(image=image, bboxes=bboxes)
        transformed_image = transformed['image']
        transformed_bboxes = transformed['bboxes']        
        tot_objs = len(bboxes)
        if tot_objs != 0:        
            if tot_objs > 1:
                transformed_bboxes = multi_obj_bb_yolo_conversion(transformed_bboxes, classes)
                save_aug_lab(transformed_bboxes, out_lab_pth, transformed_file_name + ".txt")
            else:
                transformed_bboxes = [single_obj_bb_yolo_conversion(transformed_bboxes[0]), classes]
                save_aug_lab(transformed_bboxes, out_lab_pth, transformed_file_name + ".txt")
            save_aug_image(transformed_image, out_img_pth, transformed_file_name + ".png")             
            draw_yolo(transformed_image, transformed_bboxes)
        else:
            print("label file is empty")

**Comment by muhammad-faizan-122** [comment]
HI @howard-hihihi, apologies for late response. I think error is due to negative element in transformed bounding boxes returned by albumentation. I have updated the code, can you please try now?

**Comment by DerManjuel** [comment]
Hi, i've got the same error with my data.

These are the values of the original bbox:
` [0.02746, 0.97089, 0.054921, 0.058219, 'multitool']`

and this is the exception message I get:
```
    raise ValueError(f"Expected {name} for bbox {bbox} to be in the range [0.0, 1.0], got {value}.")
ValueError: Expected x_min for bbox (-5.000000000005e-07, 0.9417805, 0.0549205, 0.9999995, 'multitool') to be in the range [0.0, 1.0], got -5.000000000005e-07.
```

I've tried to skip the image, but ran in the same error again. It seems like the input value should not be below 0.0..

Edit:
I have printed x-values below 0.1 and found, that not every value below 0.1 causes the error.
For today I don't know how to fix the issue. If you have any idea please tell me, thanks for your time.
